/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leiturasequencialdboo;


/**
 *
 * @author Mauricio
 */
public class LivroIHM extends javax.swing.JFrame {

    /**
     * Creates new form LivroIHM
     */
    public LivroIHM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Listar Livros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.DefaultListModel modelo = new javax.swing.DefaultListModel();
        Livro umlivro = new Livro();
        jList1.setModel(modelo);
        
        if (!Erro.getErro())
        {
            umlivro = LivroDAL.getLivro();
            while(!Erro.getErro())
            {
                modelo.addElement(umlivro.getTitulo() + " - " + umlivro.getAutor());
                umlivro = LivroDAL.getLivro();
            }
        }
        else
        {
            javax.swing.JOptionPane.showMessageDialog(null,Erro.getMens());
        }
       /*
       Livro umlivro = new Livro();
       
       umlivro.setTitulo("111");
       umlivro.setAutor("111");
       umlivro.setEditora("111");
       umlivro.setAnoEdicao("111");
       umlivro.setLocalizacao("111");
       
       LivroDAL.inseriLivro(umlivro);
       
       umlivro.setTitulo("222");
       umlivro.setAutor("222");
       umlivro.setEditora("222");
       umlivro.setAnoEdicao("222");
       umlivro.setLocalizacao("222");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("333");
       umlivro.setAutor("333");
       umlivro.setEditora("333");
       umlivro.setAnoEdicao("333");
       umlivro.setLocalizacao("333");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("333");
       umlivro.setAutor("333");
       umlivro.setEditora("333");
       umlivro.setAnoEdicao("333");
       umlivro.setLocalizacao("333");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("444");
       umlivro.setAutor("444");
       umlivro.setEditora("444");
       umlivro.setAnoEdicao("444");
       umlivro.setLocalizacao("444");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("555");
       umlivro.setAutor("555");
       umlivro.setEditora("555");
       umlivro.setAnoEdicao("555");
       umlivro.setLocalizacao("555");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("666");
       umlivro.setAutor("666");
       umlivro.setEditora("666");
       umlivro.setAnoEdicao("666");
       umlivro.setLocalizacao("666");
       LivroDAL.inseriLivro(umlivro);
       umlivro.setTitulo("777");
       umlivro.setAutor("777");
       umlivro.setEditora("777");
       umlivro.setAnoEdicao("777");
       umlivro.setLocalizacao("777");
       LivroDAL.inseriLivro(umlivro);*///inserção de dados 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroIHM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroIHM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
